from prompt_toolkit.completion import Completer, Completion

# Predefined list of transaction suggestions.
classifications = [
    "Expense|Travel|Fuel",
    "Expense|Family|Dad",
    "Expense|Home Renovation|Pardi",
    "Investment|SSY|Tanushree",
    "Investment|SSY|Prisha",
    "Income|Dividend|Dividend",
    "Investment|Mutual Fund|SIP",
    "Expense|Health|Dental",
    "Expense|Shopping|Clothes",
    "Expense|Travel|Hotel",
    "Expense|Cash|ATM",
    "Expense|Bank|Fees",
    "Transfer|A/c to A/c|Chintan",
    "Expense|Food|Snacks",
    "Expense|Donation|Donation",
    "Expense|Lifestyle|Drinks",
    "Income|Mutual Fund|Withdrawal",
    "Transfer|A/c to A/c|Creditcard",
    "Expense|Food|Dinning",
    "Expense|Lifestyle|Jewellery",
    "Transfer|A/c to A/c|Ilaxi",
    "Transfer|A/c to A/c|Tanushree",
    "Transfer|A/c to A/c|Prisha",
    "Transfer|A/c to A/c|Zerodha",
    "Income|Saving Account|Interest",
    "Expense|School fees|Tanushree",
    "Expense|School fees|Prisha",
    "Expense|Health|Medicine",
    "Expense|Insurance|Term",
    "Expense|Insurance|LIC",
    "Expense|Health|Skin",
    "Expense|Travel|Bus",
    "Expense|Travel|Flight",
    "Expense|Health|OPD",
    "Expense|Health|Medical Test",
    "Income|Salary|Finastra",
    "Transfer|A/c to A/c|SBI",
    "Expense|Rent|Pune",
    "Expense|Land Purchase|Velhe",
    "Expense|Maintenance|Kharghar",
    "Income|Bank|Fees Waiver",
    "Expense|Shopping|Novelty",
    "Expense|Health|Haircut",
    "Expense|Groceries|Groceries",
    "Expense|Fintoo|Fintoo",
    "Transfer|A/c to A/c|Sunil",
    "Income|Creditcard|Cashback",
    "Expense|Bill payment|Mobile",
    "Expense|Lifestyle|Coffee",
    "Expense|Lifestyle|Bar",
    "Transfer|A/c to A/c|Unknown",
    "Expense|Bill payment|Internet",
    "Expense|Shopping|Mobile",
    "Expense|Travel|Cab",
    "Expense|Shopping|Amazon",
    "Transfer|A/c to A/c|Angelone",
    "Expense|Bill payment|Apple",
    "Expense|Groceries|Fruits",
    "Expense|Groceries|Milk",
    "Expense|Shopping|Household",
    "Expense|Lifestyle|Movie",
    "Expense|Shopping|Book",
    "Expense|Shopping|Cycle",
    "Expense|Maintenance|Car",
    "Expense|Lifestyle|OTT",
    "Transfer|A/c to A/c|Google",
    "Expense|Shopping|Gift",
    "Expense|Shopping|Electronics",
    "Expense|Shopping|Stationery",
    "Expense|Bill payment|Gas",
    "Expense|Bill payment|Electricity",
    "Expense|Maintenance|Computer",
    "Expense|Food|Juice",
    "Transfer|A/c to A/c|Neeta",
    "Transfer|A/c to A/c|Nimishaben",
    "Transfer|A/c to A/c|Pallavi",
    "Transfer|A/c to A/c|Ashish",
    "Expense|Travel|Fasttag",
    "Transfer|A/c to A/c|Renuka",
    "Expense|Lifestyle|Parlour",
    "Expense|Education|Guitar class",
    "Expense|Lifestyle|Gamezone",
    "Expense|Shopping|Utensil",
    "Expense|Servant|Pune",
    "Income|Rent|Kharghar",
    "Expense|Health|Hospital",
    "Expense|Carwash|Pune",
    "Transfer|A/c to A/c|Vicky",
    "Expense|Insurance|Car",
    "Transfer|A/c to A/c|AshwinLad",
    "Expense|Shopping|Footwear"
]

class CustomTransactionCompleter(Completer):
    def get_completions(self, document, complete_event):
        # text_before_cursor contains what the user has typed so far.
        user_input = document.text_before_cursor
        for classification in classifications:
            # Check if the typed input appears anywhere in the transaction (case-insensitive).
            if user_input.lower() in classification.lower():
                # start_position defines how much of current text should be replaced.
                yield Completion(classification, start_position=-len(user_input))
